### ISSUE TITLE
[Bug] Config to limit enchantments to magical items not working (1.19.2)

### ISSUE THREAD

**Issue by TheRealIceCracker** [ZsoltMolnarrr/SpellDamage#10]
Minecraft: 1.19.2
Fabric: 0.14.21
Spell Power: 0.9.12

The config option in enchantments.json to limit the new enchants to magical weapons or magical armor is not working, these enchants are showing up as options in the enchanting table on vanilla armor/weapons as well as armor and weapons from the Epic Knights mod.

Mod List: [https://pastebin.com/UxWBnaU9](https://pastebin.com/UxWBnaU9)

**Comment by TheRealIceCracker** [comment]
Let me know what I can do to help identify the root cause of this issue, I love your mods and would very much like to get this sorted out.

**Comment by ZsoltMolnarrr** [comment]
For enchantment limitations one of the following value can be chosen for each enchantment:
`ARMOR, MAGICAL_ARMOR, MAGICAL_WEAPON`

Please make sure you type the value correctly.
Also it is possible that another mod is causing the issue, by overriding our restriction logic.

Can you reproduce the issue only when **only** Spell Power and Epic Knight mods are installed? (and not a hundered others)

**Comment by TheRealIceCracker** [comment]
Did a bunch of testing and have confirmed that it's due to [MoreJS](https://www.curseforge.com/minecraft/mc-mods/morejs), which tracks because based on its [wiki](https://github.com/AlmostReliable/morejs/wiki), it allows you to use KubeJS to mess with enchanting events. It's interesting due to the fact that I hadn't actually started using any part of this mod, so it's definitely something it does by default.

I'm not very familiar with the Minecraft mod scene, so wondering what your thoughts are on the most appropriate way to handle this. I'm thinking I make an issue in their repository and explain the problem, linking to this issue. What do you think?

**Comment by ZsoltMolnarrr** [comment]
If enchant events are changed in any way, correct behaviour cannot be guaranteed in any way.
