### ISSUE TITLE
Fixing Ticking Entity

### ISSUE THREAD

**Issue by iLegendaryTyler** [ZsoltMolnarrr/SpellDamage#17]
When I try to join my friends server I get kicked for ticking entity. 

This is the error code

Neruina Caught Exception
java.lang.NullPointerException: Cannot read field "use_vanilla_magic_damage_type" because "net.spell_power.SpellPowerMod.attributesConfig.value" is null

When I go into the attributes file in the spell_power folder this is what I see

{
  "use_vanilla_magic_damage_type": true,
  "base_spell_critical_chance_percentage": 5.0,
  "base_spell_critical_damage_percentage": 50.0
}

So I was wondering why Neruina was kicking me from the server?

**Comment by ZsoltMolnarrr** [comment]
This problem is unheard of.
What exactly are the installed mod versions on client and server? There is likely a mismatch.

**Comment by iLegendaryTyler** [comment]
I am using the mods in DarkRPG-7.8.4. I downloaded that and haven't changed anything.

**Comment by ZsoltMolnarrr** [comment]
That version of that modpack likely contains some invalid combination of mods.
Mods inside it, likely need to be update or adjusted.
I don't see what I can do.

**Comment by iLegendaryTyler** [comment]
Ok well at least you narrowed it down for me. I appreciate the help.
