### ISSUE TITLE
Ticking Entity with new release and Lithium?

### ISSUE THREAD

**Issue by tacogerbil** [ZsoltMolnarrr/SpellDamage#18]
newest release crashes with a Ticking entity exception...
[latest.log](https://github.com/ZsoltMolnarrr/SpellPower/files/14960119/latest.log)
[crash-2024-04-12_07.33.34-server.txt](https://github.com/ZsoltMolnarrr/SpellPower/files/14960128/crash-2024-04-12_07.33.34-server.txt)

**Comment by ZsoltMolnarrr** [comment]
`extraspellattributes` either needs to be updated or removed
