### ISSUE TITLE
[Compatibility] Integration With PlayerEx?

### ISSUE THREAD

**Issue by RobertHDPotatoes** [ZsoltMolnarrr/SpellDamage#2]
I know that Spell Power Attributes is likely to change a lot as development continues, but I'd love to eventually see extra compatibility between PlayerEx and Spell Power, in the form of simply adding a new tab to PlayerEx's Attributes/Combat screen much like the Combat tab. The new third tab could be called "Magic" or "Wizardry" and would include each magic school's attribute laid out numerically, spell critical chance/damage, and spell haste via percentages, similar to how the default PlayerEx Combat tab is laid out. As long as this is added on your end, modpack makers can distribute the Spell Power attributes however they see fit through datapacks via PlayerEx, but Spell Power could also include a basic datapack that distributes attributes and can be changed by modpack makers/end users.

**Comment by ZsoltMolnarrr** [comment]
I am fairly certain the that Spell Power Attributes mod is the lower level mod, meaning the compatibility should be implemented from the other way around.
The same way as PlayerEx depends on DataAttributes, it could depend on Spell Power Attributes (as a soft dependency).

If any API additional query function is required from the Spell Power API, I am open to implement it.

**Comment by PixelatedBruh** [comment]
Speaking of this i tried to change the default value of arcane spell power attribute with the data attribute mod. but i could not get it to work
