### ISSUE TITLE
Spell School Enchantments ADD vs. MULTIPLY

### ISSUE THREAD

**Issue by fzzyhmstrs** [ZsoltMolnarrr/SpellDamage#20]
Our TSMP players were noticing today that "Energize" wasn't seeming to affect their damage very much. **Important Note: the damage is question is from an Amethyst Imbuement spell, not a Spell Engine one, so the compatibility layer is also there**

Looking into the Spell Power source, it seems like the enchantments are set up in the configs to be `MULTIPLY` type, but in the enchantments themselves, are `ADD`. In the case of Energize, that would mean a full set of Energize 5 gear would only give +0.6 spell power (at default config levels, 0.03 * 20). This doesn't seem intentional to me, as even starter Wizards gear gives more base spell power than this.

![image](https://github.com/ZsoltMolnarrr/SpellPower/assets/72876796/b0fc92d7-2200-4a68-9d41-017b930b62c0)

![image](https://github.com/ZsoltMolnarrr/SpellPower/assets/72876796/228f325d-d063-4c25-9248-b8a8cb27ae15)

**Comment by fzzyhmstrs** [comment]
Considering instead `MULTIPLY` in the enchantment definition, you would achieve 1.6x multiplier, 60% increased spell power, which seems much more in line with expectations.

**Comment by fzzyhmstrs** [comment]
Ok, so I found out where I was getting confused, I missed that there are actually two layers of operation in play. The complaint from the player is from the change in the enchantment behavior as far as I can tell.

**Comment by ZsoltMolnarrr** [comment]
Hello!
Great to hear the issue is resolved.
These configurations are fairly simple, tested many times, I would be surprised to see them being buggy. :)
