### ISSUE TITLE
[Compatibility] Spell Oil'd weapons are not eligible for spellpower enchants

### ISSUE THREAD

**Issue by SargeRyong** [ZsoltMolnarrr/SpellDamage#21]
Applying a Spell Oil from spellbladesnext to any melee weapon turns it into a spell catalyst.  However, they remain ineligible for spellpower enchantments.  

I thought I'd work around the issue by changing the requirement in the config from     

`"requires": "MAGICAL_WEAPON",`
to
`"requires": "WEAPON",`

but it seems this is not a valid value.   Is there a way around this currently?

**Comment by ZsoltMolnarrr** [comment]
This doesn't seem to be a bug of Spell Power Attributes.
Spell Power Attributes is a low level API, hence it is incorrect to add supporting into SPA for high level mods, such as the mentioned one.
