### ISSUE TITLE
Inquiry Regarding Plugin Upgrade to Version 1.20.4

### ISSUE THREAD

**Issue by Trackhe** [ZsoltMolnarrr/SpellDamage#23]
Hey i m interested in a 1.20.4 version of your mods. Do you have any hint or information about your plans for updates?

Best regards MN(Trackhe)

**Comment by ZsoltMolnarrr** [comment]
Hello!
This mod serves as a foundation and compatibility tool for the RPG Series projects, without the content mods it serves zero purpose.
The plan is to update RPG Series to 1.21.X, within a few weeks.

**Comment by Trackhe** [comment]
I understand thank you.
