### ISSUE TITLE
1.20.4 support?

### ISSUE THREAD

**Issue by Jack-Chronicle** [ZsoltMolnarrr/SpellDamage#26]
Would it be possible to update this to allow it to work on 1.20.4 Minecraft?
Not sure if there's some changes that were made that make it impossible or it's just a simple change to allow it to work (and maybe the other RPG series APIs and mods)

**Comment by ZsoltMolnarrr** [comment]
Hello!
This mod serves as a foundation and compatibility tool for the RPG Series projects, without the content mods it serves zero purpose.
The plan is to update RPG Series to 1.21.X, within a few weeks.
