### ISSUE TITLE
[Forge] No book slot

### ISSUE THREAD

**Issue by doemty** [ZsoltMolnarrr/SpellDamage#29]
Using Forge 47.2.32 and Sinytra 1.0.0. beta 43. Is it possible to nake compability with Curious? Or at least Trinkents (in case if it is compatible with Curious and Forge)
So the problem is in unability to use spell books.
![image](https://github.com/user-attachments/assets/f17505b4-5f18-4218-bbd3-8bc0815894a8)

**Comment by ZsoltMolnarrr** [comment]
Install Trinkets to have the SpellBook slot.
Without Trinkets, just hold the spellbook in the offhand slot.

**Comment by ZsoltMolnarrr** [comment]
Also this is a Spell Engine feature. :)

**Comment by doemty** [comment]
> Install Trinkets to have the SpellBook slot. Without Trinkets, just hold the spellbook in the offhand slot.

Oh Lord, really my silly bad :D
Thx! Love your mods! <3

**Comment by doemty** [comment]
> Also this is a Spell Engine feature. :)

Srry! :>
