### ISSUE TITLE
Crashing on world launch

### ISSUE THREAD

**Issue by DeacffinatedSoup** [ZsoltMolnarrr/SpellDamage#31]
![image_2024-08-16_190458811](https://github.com/user-attachments/assets/7ce4fc7a-065b-4b67-a1b8-be66937ea355)

I get this whenever I launch my world. Does anyone know how to fix it?

**Comment by ZsoltMolnarrr** [comment]
This normally doesn't happen.

I suspect this is coming from some kind of installation problem.

I recommend using the CurseForge app, for making custom modpacks.
