### ISSUE TITLE
GPL-3.0 license

### ISSUE THREAD

**Issue by justliliandev** [ZsoltMolnarrr/SpellDamage#4]
The GPL-3.0 license makes it impossible to add any kind of integration from a non GPL-3.0 mod. [a short explanation here](https://opensource.stackexchange.com/questions/1640/if-im-using-a-gpl-3-library-in-my-project-can-i-license-my-project-under-mit-l)

You also link your mod with minecraft which is a non GPL-3.0 program. However, the GPL-3.0 license doesn't allow you to do that (making it impossible to apply to minecraft mods). [see here](https://www.gnu.org/licenses/gpl-faq.html#GPLIncompatibleLibs)

I would appreciate it, if you would change the license to something more usable for minecraft mods and libs (like MIT).

**Comment by ZsoltMolnarrr** [comment]
Hello!

_The GPL-3.0 license makes it impossible to add any kind of integration from a non GPL-3.0 mod._
I think this is not true. According to best of my understand GPLv3 requires you to stay open source, but doesn't force you to the same licence.
https://opensource.stackexchange.com/a/4557

The idea is that no closed source variants should be allowed, do you know a specific licence that would better suit this purpose?

I am open to fix this issue, and extend the solution to the spell engine too.

**Comment by justliliandev** [comment]
You probably want to use a weaker copyleft.
The [LGPL 3.0](https://www.gnu.org/licenses/lgpl-3.0-standalone.html) allows all kinds of mods to link to this mod as a library and is also a commonly used license for minecraft modders and doesn't have any of the problems of GPL-3.0 when combined with Minecraft.
This would allow all mods (even ARR ones) to use this mod as a library, which can be a benefit.
There are (to my knowledge) no commonly used licenses, that have a copyleft and forcing the linked to mods (mods, that depend on this) to be open source, while not being incompatible with Minecraft.

As always: I'm not a lawyer, but LGPL seems like a reasonable license to use

**Comment by ZsoltMolnarrr** [comment]
This specific library is moving on to LGPLv3, however
https://choosealicense.com (hosted by GitHub) describes GPL-3.0 as:
_The [GNU GPLv3](https://choosealicense.com/licenses/gpl-3.0/) also lets people do almost anything they want with your project, **except** distributing closed source versions._

This to me seems to be contradictory to what you state: _impossible to add any kind of integration from a non GPL-3.0 mod_

Could you address this please?

**Comment by ZsoltMolnarrr** [comment]
As the license has been changed, I close the issue, but feel free to continue the conversation, or join Discord to do so.

**Comment by justliliandev** [comment]
> This to me seems to be contradictory to what you state: impossible to add any kind of integration from a non GPL-3.0 mod

yep, that was me messing up the difference between GPL and GPL-compatible Licenses. sorry for causing confusion on that part
