### ISSUE TITLE
Suggestion to Add "Generalist" Spell School

### ISSUE THREAD

**Issue by AetheriMC** [ZsoltMolnarrr/SpellDamage#5]
Hello,

Would it be possible to add in a "General" spell school that can be assigned to weapons, so that spells from all schools can be bound to that weapon instead of only allowing for fire spells to attach to fire weapons for example?

If this is already possible, I apologize.

Thanks in advance. Love the work!

**Comment by ZsoltMolnarrr** [comment]
Hello!
No thats not possible, nor is it the scope of this library.
There is a change planned for the Spell Engine to achieve more flexible weapon-spell assignment.

**Comment by AetheriMC** [comment]
Understood. Thank you for the feedback!
